locals {
  # ネストしたヒアドキュメントの中でTerraformの制御構文(%{ for ~})を直接
  # 使うと空白除去の影響でヒアドキュメント終端が壊れる問題が過去にあったため、
  # 事前に1つの文字列としてレンダリングし、単純な${}展開のみで埋め込む。
  delete_route_lines = var.delete_autogenerated_kernel_route ? join("\n", [for ip in var.server_allowed_ips : "ip route del ${ip} dev ${var.wireguard_interface} 2>/dev/null || true"]) : ""
}

resource "null_resource" "wireguard" {
  triggers = {
    host                       = var.host
    wireguard_address          = var.wireguard_address
    server_endpoint            = var.server_endpoint
    server_public_key          = sha256(var.server_public_key)
    allowed_ips                = join(",", var.server_allowed_ips)
    delete_autogenerated_route = var.delete_autogenerated_kernel_route
    setup_version              = "12"
  }

  connection {
    type        = "ssh"
    host        = var.host
    user        = var.ssh_user
    private_key = var.ssh_private_key
  }

  provisioner "file" {
    content     = <<-SCRIPT
      #!/bin/bash
      set -eo pipefail
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      export DEBIAN_FRONTEND=noninteractive
      umask 077
      exec > >(tee -a /tmp/wireguard-setup.log) 2>&1

      # 同一ホストに対してこのモジュールが複数回呼び出される場合(k8s1のalice向け
      # module.wireguardとionos向けmodule.wireguard_ionosなど)、terraformは
      # 独立したリソースとして並列にapplyするため、同時にapt-getが実行され
      # dpkgロックの競合(exit code 100)でどちらかが失敗することがある。
      # 専用のロックファイルでapt-get呼び出し自体を直列化する
      # (apt自身が使う/var/lib/apt/lists/lockを外側からもflockすると、
      # apt-get内部のロック取得と二重にロックしようとしてデッドロックするため
      # 別のロックファイルを使う)。
      #
      # このflockはこのモジュール自身の複数呼び出し間(wireguard/wireguard_ionos)
      # の競合しか防げない。OS自身のunattended-upgradesや、同一ホスト上の他モジュール
      # (control_plane/keepalived/knot等)のapt-getとも競合しうる。事前にdpkgロックが
      # 空くのを待っても、チェックした直後に別プロセスが取ってしまうTOCTOU競合が
      # あるため、実際にapt-getが失敗した場合はリトライする。
      wait_for_dpkg_lock() {
        for i in $(seq 1 60); do
          if ! fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock >/dev/null 2>&1; then
            return 0
          fi
          echo "dpkg lock is held by another process, waiting... ($i/60)"
          sleep 5
        done
        echo "timed out waiting for dpkg lock" >&2
        return 1
      }

      apt_get_retry() {
        for attempt in $(seq 1 20); do
          wait_for_dpkg_lock
          if flock /tmp/wireguard-module-apt.lock "$@"; then
            return 0
          fi
          echo "apt-get command failed (attempt $attempt/20), retrying in 5s..." >&2
          sleep 5
        done
        echo "apt-get command failed after 20 attempts" >&2
        return 1
      }

      apt_get_retry apt-get update -y
      apt_get_retry apt-get install -y wireguard

      # ionos側がこのノードの公開鍵を非rootユーザー経由のSSHで取得する
      # (hardware/ionosのdata.external.k8s1_wireguard_public_key等)ため、
      # ディレクトリ自体は700ではなく711(traverse可)にし、publickeyだけ
      # 世界読み取り可能にする。privatekeyはファイル自体を600に制限して
      # いるため、711でも秘匿性は保たれる(hardware/soichiroの同種の
      # 修正と同じ対応)。
      install -d -m 711 /etc/wireguard

      if [ ! -f /etc/wireguard/privatekey ]; then
        wg genkey > /etc/wireguard/privatekey
        wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
      fi
      chmod 600 /etc/wireguard/privatekey
      chmod 644 /etc/wireguard/publickey

      private_key=$(cat /etc/wireguard/privatekey)

      cat > /etc/wireguard/${var.wireguard_interface}.conf <<WG_EOF
      [Interface]
      Address = ${var.wireguard_address}
      PrivateKey = $private_key

      [Peer]
      PublicKey = ${var.server_public_key}
      AllowedIPs = ${join(", ", var.server_allowed_ips)}
      Endpoint = ${var.server_endpoint}
      PersistentKeepalive = ${var.persistent_keepalive}
      WG_EOF
      chmod 600 /etc/wireguard/${var.wireguard_interface}.conf

      systemctl enable wg-quick@${var.wireguard_interface}
      systemctl restart wg-quick@${var.wireguard_interface}

      # wg-quickがPeerのAllowedIPsから自動生成したOSカーネルルートを削除する。
      # WireGuard自体の暗号ルーティング(AllowedIPsによるピア認証)には影響しない
      # (OSのルーティングテーブルとは独立した、WireGuardカーネルモジュール内部の判定のため)。
      ${local.delete_route_lines}

      echo "=== WireGuard status ==="
      wg show ${var.wireguard_interface}
      echo "=== Public key ==="
      cat /etc/wireguard/publickey
    SCRIPT
    destination = "/tmp/wireguard-setup.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "echo '${var.sudo_password}' | sudo -S bash /tmp/wireguard-setup.sh && rm -f /tmp/wireguard-setup.sh",
    ]
  }
}
