variable "host" {
  type = string
}

variable "ssh_user" {
  type = string
}

variable "ssh_private_key" {
  type      = string
  sensitive = true
}

variable "sudo_password" {
  type      = string
  sensitive = true
}

variable "wireguard_address" {
  description = "WireGuard インターフェースのアドレス (例: 172.31.255.11/24)"
  type        = string
}

variable "wireguard_interface" {
  type    = string
  default = "wg0"
}

variable "server_public_key" {
  description = "接続先 (Alice) の WireGuard 公開鍵"
  type        = string
}

variable "server_endpoint" {
  description = "接続先の WireGuard エンドポイント (IP:port)"
  type        = string
  default     = "161.248.62.66:51820"
}

variable "server_allowed_ips" {
  description = "WireGuard トンネル経由でルーティングするIPレンジ"
  type        = list(string)
  default     = ["172.31.255.0/24"]
}

variable "persistent_keepalive" {
  type    = number
  default = 25
}

variable "delete_autogenerated_kernel_route" {
  description = "wg-quickがPeerのAllowedIPsから自動生成するOSカーネルルートを、インターフェース起動直後に明示的に削除する。WireGuard自体の暗号ルーティング(AllowedIPsによるピア認証・パケット受け入れ判定)には影響しない(それはWireGuardカーネルモジュール内部の判定でありOSのルーティングテーブルとは別物)。BGP等で同じ宛先へのより適切な経路が別途存在し、このノード自身がAllowedIPs宛に自発的な通信をする必要が無い場合にtrueにする(自発的な通信がある場合、この削除によりデフォルトルート等の意図しない経路にフォールバックしてしまうため、trueにしないこと)"
  type        = bool
  default     = false
}

variable "table_off" {
  description = "true にすると、wg-quick の設定に `Table = off` を入れ、AllowedIPs から自動で作るカーネル経路を、インターフェース起動のたびに作らせない。delete_autogenerated_kernel_route は、セットアップ時に 1 回だけ経路を削除するので、ノード / wg-quick の再起動で経路が復活する(2026-10-05、k8s2 の復旧で復活し、`172.31.254.0/24` が iBGP に誤って広告された)。AllowedIPs 自体(WireGuard の暗号鍵ルーティング)は変わらない。必要な経路は extra_post_up で足す"
  type        = bool
  default     = false
}

variable "extra_post_up" {
  description = "wg-quick の PostUp に足すコマンド(1 行ずつ)。table_off = true のとき、AllowedIPs の自動経路の代わりに、必要な経路を足すために使う。%i はインターフェース名に展開される"
  type        = list(string)
  default     = []
}
