variable "host" {
  type = string
}

variable "ssh_user" {
  type = string
}

variable "ssh_private_key" {
  type      = string
  sensitive = true
}

variable "sudo_password" {
  type      = string
  sensitive = true
}

variable "wireguard_address" {
  description = "WireGuard インターフェースのアドレス (例: 172.31.255.11/24)"
  type        = string
}

variable "wireguard_interface" {
  type    = string
  default = "wg0"
}

variable "server_public_key" {
  description = "接続先 (Alice) の WireGuard 公開鍵"
  type        = string
}

variable "server_endpoint" {
  description = "接続先の WireGuard エンドポイント (IP:port)"
  type        = string
  default     = "161.248.62.66:51820"
}

variable "server_allowed_ips" {
  description = "WireGuard トンネル経由でルーティングするIPレンジ"
  type        = list(string)
  default     = ["172.31.255.0/24"]
}

variable "persistent_keepalive" {
  type    = number
  default = 25
}

variable "delete_autogenerated_kernel_route" {
  description = "wg-quickがPeerのAllowedIPsから自動生成するOSカーネルルートを、インターフェース起動直後に明示的に削除する。WireGuard自体の暗号ルーティング(AllowedIPsによるピア認証・パケット受け入れ判定)には影響しない(それはWireGuardカーネルモジュール内部の判定でありOSのルーティングテーブルとは別物)。BGP等で同じ宛先へのより適切な経路が別途存在し、このノード自身がAllowedIPs宛に自発的な通信をする必要が無い場合にtrueにする(自発的な通信がある場合、この削除によりデフォルトルート等の意図しない経路にフォールバックしてしまうため、trueにしないこと)"
  type        = bool
  default     = false
}
